### ISSUE TITLE
So is this just a simple way to get inputs from controllers?

### ISSUE THREAD

**Issue by KellanHiggins** [VRStudios/Unity3D-XRInput#1]
I've been looking at a lot of of forums complaining about Unity XR vs SteamVR and banging my head against the wall just trying to get the trigger strength out of a Vive wand.

Will this make it easy to grab everything I need and not have to worry about whatever the heck Valve and Unity are doing?

**Comment by zezba9000** [comment]
Yes this API universalizes Input from different vendors into a single API.

Just look at this script and the "How to get Input" section in the readme.
https://github.com/VRStudios/Unity3D-XRInput/blob/master/Assets/VRstudios/Scenes/Test%20Assets/TestInput.cs

I would just clone the repo set what XR profile settings you want to test with and try the Example scene. Getting input is very basic.

**Comment by KellanHiggins** [comment]
Holy crap amazing. Thank you so much. I'll check it out. Happy to give you feedback if you want it too :).

**Comment by zezba9000** [comment]
Ya if you find any bugs or issues would be happy to hear about them :)

**Comment by KellanHiggins** [comment]
So far I am blown away, imported it into my project with very little hassle. I think there were a few fixes I had to make but the Unity XR checks did that on their own.

Within a few minutes I could just read the inputs from my Vive. Exactly what I wanted. Took me days to set up the same thing with the SteamVR's Plugin. Thanks so much for putting this together.
