### ISSUE TITLE
How hard is it to remove headsets that you don't want to support?

### ISSUE THREAD

**Issue by KellanHiggins** [VRStudios/Unity3D-XRInput#2]
For example, I don't want to use HTC's Wave simply because I can't turn off a warning it fires every time I hit play. If I try and comment out the warning, it rewrites the file cause apparently it is like that.

I haven't looked into adding defines based on some file or doing something else to limit adding platforms that I literally can't support due to how I am releasing the game.

Thoughts on that?

Other than this, so far this thing is AWESOME.

**Comment by zezba9000** [comment]
You don't have to support any HMD you don't want to. Wave plugin stuff isn't required.
Just use the package to install the initial bits you need: https://github.com/VRStudios/Unity3D-XRInput/releases

Or are you asking something else?

**Comment by KellanHiggins** [comment]
Nope you've got it. However I don't understand using the package to install the bits I need. Should I not download the latest package which is 1.0.9? I figured I should download the latest one to get the most up to date code.

I figured it wasn't required, I am just trying to make sure I can cleanly remove the Wave Plugin and nothing will break. Haven't tried doing that yet TBH.

**Comment by zezba9000** [comment]
You should be installing 1.0.9 (which is the latest), then setting up 3rd party dependencies as needed such as SteamVR, etc. You don't need to setup other 3rd party stuff unless you need support for it (no need to import Wave SDK stuff when you don't need it etc).

The package file in the releases area is the core of the XRInput plugin. **This repo (if you're cloning) is setup supporting all HMD's for testing but only the package files from the releases page are required.**

Just import 1.0.9 .unitypackage via the file menu "**Assets > Import Package > Custom Package**" then look at the readme to setup support for OpenVR if wanted. Or you can use OpenXR BUT for SteamVR I recommend using [OpenVR ](https://github.com/ValveSoftware/unity-xr-plugin/releases) tracking stuff as its more compatible with Cosmos if you need support for that.

**Comment by KellanHiggins** [comment]
Okay, I took the plunge and just removed the Wave and Pico packages and nothing seems to have broken. I haven't tried to run the VR yet (it's late) but it looks like I am getting no errors.

Great job. This thing is a million times easier than SteamVR's plugin. I couldn't even get that to work without tearing my hair out.
