### ISSUE TITLE
Any plans to reduce the verbose debuging?

### ISSUE THREAD

**Issue by KellanHiggins** [VRStudios/Unity3D-XRInput#3]
Hi,

Still using this and it is great. Are there any plans to reduce the verbose debugging peppered throughout the code? I find it annoying to constantly get information printed to the console when I am testing.

Can I suggest adding a debug define that the programmer can turn on and off?

Cheers,

**Comment by KellanHiggins** [comment]
Oh whoops, I see that the Test Input was doing a lot of debug posting. But there are a few other debug messages that pop up every time you start up the player.

**Comment by zezba9000** [comment]
Ya the TestInput.cs file is meant to print out input data for testing.

**Which logs do you feel are verbose?**

Some I feel are important such as printing the version numbers of OpenVR lib etc in case some compatibility issue came up.

The only other ones happen when using UnityEngine_XR Input stuff which prints out device names of connected controllers. The reason for this is if some a controller reports an invalid name, it could be the reason some device features fail to work (which could happen with prototype controllers for example). Knowing what the name is could help a lot from a users log.

**It would be easy to make an option to disable all XRInput logging. Which I can add.**

**Comment by KellanHiggins** [comment]
Disabling all XRInput logging would be great! I tend to use the console to figure stuff out and any logging can hide the information I am trying to see and slow me down. I just commented out everything I saw for now.

Thanks!

**Comment by KellanHiggins** [comment]
Wow, you work fast! I saw the new release! Thanks so much.

**Comment by zezba9000** [comment]
Ok published changes: https://github.com/VRStudios/Unity3D-XRInput/releases
There is now a checkbox on XRInput script that allows you to disable all info logs (critical error logs don't get disabled FYI)
