### ISSUE TITLE
XRInput for UGUI

### ISSUE THREAD

**Issue by Wallen27** [VRStudios/Unity3D-XRInput#4]
This really helped me tremendously, I was able to quickly move the Oculus project to SteamVR.  However, I ran into another problem, SteamVR does not support interaction with native UGUI, its examples are all done by adding colliders.  This makes me very depressed. Do you have any suggestions on this problem?  Thanks for XRInput anyway!

**Comment by zezba9000** [comment]
XRInput is not designed to handle UI interactions as thats a totally different abstraction.
XRInput simply gets you back input data from controllers in a simple to use way.

You need to implement UI interactions yourself.
